### ISSUE TITLE
[DOCS] Release checklist (8.1) 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#1632]
Checklist:

- [ ]  What's New?
     -  Ensure `include` tags are included in file for inclusion in `stack-docs` [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

- [ ] Release notes merged https://github.com/elastic/security-docs/pull/1633
**IMPORTANT:** Merge the Security release notes PR _before_ merging the Stack docs PR. The Stack Docs PR contains links that point to anchors in the Security release notes PR and (the links) won't resolve until the Security PR is merged with `main` and the `8.1` release notes page is published on the docsite. 
     - Ensure any breaking changes are included in `stack-docs` [Breaking Changes] https://github.com/elastic/stack-docs/pull/2076
- [ ] All topics updated to reflect the new UI navigation
- [ ]  All API changes merged
- [ ] D&R PRs merged and backported
- [ ] Threat Hunting PRs merged and backported
- [ ] Endpoint PRs merged and backported
- [ ] OLM PRs merged and backported 
- [ ]  Bug issues addressed
- [ ]  Update the docs release dev issue with appropriate PR numbers
- [ ]  Review and merge `8.1` prebuilt rules
- [ ]  Verify that merged doc updates display correctly in `main` and `8.1`

**Comment by jmikell821** [comment]
8.1 is released!
