### ISSUE TITLE
[DOCS] Release checklist (8.2)

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#1817]
Checklist:

- [x] The `coming` tag was removed from the "Blocklist" topic - Done in #1887.
- [x]  What's New?
     -  Ensure `include` tags are included in file for inclusion in `stack-docs` [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

- [x] Release notes merged: https://github.com/elastic/security-docs/pull/1828
- [x] Merge https://github.com/elastic/stack-docs/pull/2099 to ensure Security breaking changes are included in `stack-docs`
**IMPORTANT:** Both of the following requirements must be met for the stack docs PR to build:
  - The 8.2 Security release notes PR merged into main and backported to the 8.2 branch.
  - The 8.2 Security release notes page will need to be built/published on the 8.2 branch and available on the public docsite.
- [x] All topics updated to reflect the new UI navigation
- [x]  All API changes merged
- [x] D&R PRs merged and backported
- [x] Threat Hunting PRs merged and backported
- [x] Endpoint PRs merged and backported
- [x] OLM PRs merged and backported 
- [x]  Bug issues addressed
- [x]  Update the docs release dev issue with appropriate PR numbers
- [x]  Review and merge `8.2` prebuilt rules
- [x]  Verify that merged doc updates display correctly in `main` and `8.2`

**Comment by jmikell821** [comment]
`8.2` was released! 🎉
