### ISSUE TITLE
[DOCS] Release checklist (8.3) 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2021]
Important Links: 

Project boards/Meta checklists: 

- D&R: 
   - Rules area: https://github.com/elastic/security-team/issues/3535
   - Alerts area: https://github.com/orgs/elastic/projects/698/views/11
- OLM: https://github.com/elastic/security-team/issues/3300
- Threat Hunting: 
   - Investigations: [Project board here](https://github.com/orgs/elastic/projects/583/views/34) and [here](https://github.com/orgs/elastic/projects/583/views/14)
   - Explore: [Project board](https://github.com/orgs/elastic/projects/711/views/1?filterQuery=is%3Aissue+status%3ADone)
- AWP:
- Cloud Security Posture:
- Platform: https://github.com/elastic/security-team/issues/3596
- ResponseOps: [Project board](https://github.com/orgs/elastic/projects/611/views/18) and [8.3 Cases planning](https://docs.google.com/document/d/1XhzYnyLkpEmfWk2fAx7uWPZvr6oVfLvCrCKJNkD6AFU/edit#heading=h.2f176d2119sm)   

Checklist:

- [ ] What's New?

     -  Ensure `include` tags are included in file for inclusion in `stack-docs` [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

- [x] Release notes merged: https://github.com/elastic/security-docs/pull/2030
- [ ] Merge `stack-docs` PR to ensure Security breaking changes are included in `stack-docs`: https://github.com/elastic/stack-docs/pull/2148

     **IMPORTANT:** Both of the following requirements must be met for the stack docs PR to build:
    - [ ]  The 8.3 Security release notes PR merged into main and backported to the 8.3 branch. 
    - [ ]  The 8.3 Security release notes page will need to be built/published on the 8.3 branch and available on the public docs site.  

- [ ] Ensure any UI navigation changes are merged
- [ ] API changes merged
- [ ] D&R PRs merged and backported
- [ ] Threat Hunting PRs merged and backported
- [ ] Endpoint PRs merged and backported
- [ ] OLM PRs merged and backported 
- [x] AWP PRs merged and backported
- [x] Cloud Security Posture PRs merged and backported
- [ ] Bug issues addressed
- [ ] Update the docs release dev issue with appropriate PR numbers
- [x] Review and merge `8.3` prebuilt rules
- [ ] Verify that merged doc updates display correctly in `main` and `8.3`
- [ ] Verify that [screenshots involving redesigned KQL bar](https://github.com/elastic/security-docs/issues/2031) are still accurate (no further UI changes later in the release cycle)
- [ ] Verify whether new threat intelligence (TI) integrations have been added to the Integrations page
  - As of 06/06/22, no new TI integrations have been added.
