### ISSUE TITLE
META: Rename `Endpoint Security` to `Endpoint and Cloud Security`

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2025]
With the addition of cloud security, we are renaming the `Endpoint Security` integration to `Endpoint and Cloud Security`.

### Component docs issues:
- [x] https://github.com/elastic/docs/issues/2444 (PR: [#2445](https://github.com/elastic/docs/pull/2445))
- [x] https://github.com/elastic/security-docs/issues/2046 (PR: [#2059](https://github.com/elastic/security-docs/pull/2059))
- [x] https://github.com/elastic/security-docs/issues/2032 (PR: [#2075](https://github.com/elastic/security-docs/pull/2075))

### Related dev issues/PRs:
- https://github.com/elastic/security-team/issues/3928
- https://github.com/elastic/kibana/pull/132752

![image](https://user-images.githubusercontent.com/57149392/170546504-4a578d4f-3163-4a82-b0f6-f0bb7ae05106.png)

### To do: 

- [x] Ensure all screenshots that mention the integration are updated
- [x] Update `endpoint-sec` [attribute](https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc#L234) to reflect new name. This involves creating a new attribute (`endpoint-cloud-sec`) and adding that reference (per #2046). 
- [x] Update hard-coded references to "Endpoint Security" to use the new attribute (`endpoint-cloud-sec`).
- [x] Update [Install Endpoint Sec integration](https://www.elastic.co/guide/en/security/8.2/install-endpoint.html) topic and all other docs that reference `Endpoint Security`. Search results [here](https://www.elastic.co/search?q=%22endpoint%20security%22&size=n_20_n&filters%5B0%5D%5Bfield%5D=website_area&filters%5B0%5D%5Bvalues%5D%5B0%5D=documentation&filters%5B0%5D%5Btype%5D=all&filters%5B1%5D%5Bfield%5D=product_name&filters%5B1%5D%5Bvalues%5D%5B0%5D=Security&filters%5B1%5D%5Btype%5D=all&filters%5B2%5D%5Bfield%5D=product_version&filters%5B2%5D%5Bvalues%5D%5B0%5D=8.2&filters%5B2%5D%5Btype%5D=all).

**Comment by joepeeples** [comment]
Closing this issue as all tasks have been completed and merged, for both Elastic Security and Observability/Fleet docs.
