### ISSUE TITLE
[DOCS] Release Checklist (8.4)

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2224]
Project boards/Meta checklists:

- D&R

   - Rules area: https://github.com/elastic/security-team/issues/4239

   - Alerts area: https://github.com/orgs/elastic/projects/698/views/13
      - Docs only: https://github.com/orgs/elastic/projects/698/views/14

- OLM:  https://github.com/elastic/security-team/issues/4032

- Threat Hunting:

   - Investigations: [Project board](https://github.com/orgs/elastic/projects/583/views/14)

  - Explore: [Project board](https://github.com/orgs/elastic/projects/711/views/1?filterQuery=is%3Aissue+status%3ADone)

- AWP:
  - [Project board](https://github.com/orgs/elastic/projects/828/views/1)

- Cloud Security Posture:

- Platform: https://github.com/elastic/security-team/issues/3964

- ResponseOps | Cases: 
   - [GH issues filter](https://github.com/elastic/kibana/pulls?q=is%3Apr+label%3AFeature%3ACases+label%3Av8.4.0)
   - [8.4 planning document](https://docs.google.com/document/d/1L4whJuk5C8QxdFVWbPRi1kzOGmfMttQc-GGEAZ-T67I/edit#heading=h.2f176d2119sm)
   - [Project board](https://github.com/orgs/elastic/projects/611/views/23) 

- Asset Management: https://github.com/elastic/security-team/issues/3900 

- Protections Experience: 

Checklist:

- [ ] What's New?

     - [ ] Ensure include tags are included in file for inclusion in stack-docs [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

 

- [ ] Release notes merged: 

 

- [ ] Merge `stack-docs` PR to ensure Security breaking changes are included in stack-docs: 

    **IMPORTANT:** Both of the following requirements must be met for the stack docs PR to build:

     - [ ] The 8.4 Security release notes PR merged into main and backported to the 8.4 branch.

     - [ ] The 8.4 Security release notes page will need to be built/published on the 8.4 branch and available on the public docs site.

 - [ ] Ensure all new navigation menu changes are updated in docs 

- [ ]  API changes merged

- [ ] D&R PRs merged and backported

- [ ]  Threat Hunting PRs merged and backported

- [ ] Endpoint PRs merged and backported

 - [ ] OLM PRs merged and backported

- [ ] AWP PRs merged and backported

- [ ] Cloud Security Posture PRs merged and backported

- [ ] ResponseOps PRs merged and backported

- [ ]  Bug issues addressed

- [ ] Update the docs release dev issue with appropriate PR numbers

- [ ]  Review and merge 8.4 prebuilt rules

- [ ]  Verify that merged doc updates display correctly in main and 8.4
