### ISSUE TITLE
[META] Grouped navigation menu

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2237]
Issue: https://github.com/elastic/kibana/issues/136732
PR: https://github.com/elastic/kibana/pull/136819

In `8.3`, grouped navigation was an option in advanced settings. In `8.4`, this setting will be enabled by default. 

To do: 

- [ ] Remove the [grouped navigation topic](https://www.elastic.co/guide/en/security/current/grouped-nav-ui.html) from the TOC, but move contents into [Elastic Security UI topic](https://www.elastic.co/guide/en/security/current/es-ui-overview.html). 
- [ ] Update [Elastic Security UI topic](https://www.elastic.co/guide/en/security/current/es-ui-overview.html) to remove old content and include new nav updates. 
- [ ] Track and update all topics, including images, that require menu changes. See [Google spreadsheet](https://docs.google.com/spreadsheets/d/1ZxgpS-p2yFrBbCrngiLgwusVxG3AYW8OSR-zyZlTtLw/edit?usp=sharing).  
- [ ] Update [advanced settings topic](https://www.elastic.co/guide/en/security/current/advanced-settings.html#_enable_grouped_navigation) that mentions grouped navigation to "Disable grouped navigation" since it'll be enabled by default. 

Old nav: 
![2022-08-01_10-59-06](https://user-images.githubusercontent.com/57149392/182247636-2d2ed5ee-3a82-4ad6-9a52-64c5fd8ded94.png)

New nav: 
![2022-08-01_10-59-55](https://user-images.githubusercontent.com/57149392/182247672-217f230d-5ddb-4c14-95df-eaef5a37192a.png)

**Note:** Users can still disable the navigation at `Stack Management > Advanced Settings > Security Solution > New streamlined navigation`.
