### ISSUE TITLE
[DOCS] Rule creation enhancements checklist 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2258]
Gathering all [create rule](https://www.elastic.co/guide/en/security/current/rules-ui-create.html) enhancements into a single checklist for visibility. 

- [x] https://github.com/elastic/security-docs/issues/1832
- [x] https://github.com/elastic/security-docs/issues/2196
- [ ] https://github.com/elastic/security-docs/issues/2208
- [x] https://github.com/elastic/security-docs/issues/2227
- [x] https://github.com/elastic/security-docs/issues/2257
