### ISSUE TITLE
[DOCS] [META] Rename integration to "Elastic Defend"

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2463]
## Description 

Per https://github.com/elastic/security-team/issues/4759, we are renaming the `Endpoint and Cloud Security` integration to `Elastic Defend`.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/87339667/190425530-32028e10-7247-4d81-875d-8f0612d777b4.png">

### Component docs issues and tasks:
_(Note that some issues require updating content in other repos besides elastic/security-docs.)_

- [x] https://github.com/elastic/docs/issues/2516
- [x] https://github.com/elastic/security-docs/issues/2464
- [x] https://github.com/elastic/security-docs/issues/2465
- [x] Update references in Observability/Fleet docs (https://github.com/elastic/observability-docs/issues/2326)
- [x] ~~Update references in Getting Started pages ([SIEM](https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-siem-security.html) and [endpoint](https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-endpoint-security.html)) (elastic/tech-content)~~ (these pages are getting revamped soon; no need to update)
- [x] https://github.com/elastic/security-docs/issues/2457 -- AWP team is developing it, but onboarding is for both cloud and endpoint workflows
- [x] Clarify language: explicit scenarios of when to use `Elastic Defend`, `Elastic Agent`, `Elastic Endpoint`, etc.

### Related issues/PRs: 

- Main dev issue for Security Team:
   https://github.com/elastic/security-team/issues/4759

- Onboarding - Cloud: 
   https://github.com/elastic/security-team/issues/3981

- Reference - previous renaming (8.3)
   https://github.com/elastic/security-docs/issues/2025

**Comment by joepeeples** [comment]
All tasks completed/resolved.
