### ISSUE TITLE
[DOCS] Release Checklist (8.5) 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2514]
Project boards/Meta checklists:

- D&R

   - Rules area: https://github.com/elastic/security-team/issues/4647

   - Alerts area: https://github.com/orgs/elastic/projects/698/views/17
      - Docs only: https://github.com/orgs/elastic/projects/698/views/18

- OLM  
   - https://github.com/elastic/security-team/issues/4206
   - Project: https://github.com/orgs/elastic/projects/585/views/3

- Threat Hunting

   - Investigations: https://github.com/orgs/elastic/projects/583/views/4

  - Explore: https://github.com/orgs/elastic/projects/711

- AWP: https://github.com/orgs/elastic/projects/828/views/28
 
- Cloud Security Posture: https://github.com/orgs/elastic/projects/866/views/6

- Platform: https://github.com/elastic/security-team/issues/4693

- ResponseOps | Cases: 
   

- Asset Management: https://github.com/elastic/security-team/issues/3900 

- Protections Experience: https://github.com/orgs/elastic/projects/758/views/15

Checklist:

- [ ] What's New?

     - [ ] Ensure include tags are included in file for inclusion in stack-docs [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

 

- [ ] Release notes merged: 

 

- [ ] Merge `stack-docs` PR to ensure Security breaking changes are included in stack-docs: 

    **IMPORTANT:** Both of the following requirements must be met for the stack docs PR to build:

     - [ ] The 8.5 Security release notes PR merged into main and backported to the 8.5 branch.

     - [ ] The 8.5 Security release notes page will need to be built/published on the 8.5 branch and available on the public docs site.

 - [ ] Ensure all new navigation menu changes are updated in docs 

- [ ]  API changes merged

- [ ] D&R PRs merged and backported

- [ ]  Threat Hunting PRs merged and backported

- [ ] Endpoint PRs merged and backported

 - [ ] OLM PRs merged and backported

- [ ] AWP PRs merged and backported

- [ ] Cloud Security Posture PRs merged and backported

- [ ] ResponseOps PRs merged and backported

- [ ]  Bug issues addressed

- [ ] Update the docs release dev issue with appropriate PR numbers

- [ ]  Review and merge 8.5 prebuilt rules

- [ ]  Verify that merged doc updates display correctly in main and 8.5
