### ISSUE TITLE
[DOCS] Analyze Event enhancements

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#261]
Meta: Data visibility roadmap 7.10: 
https://github.com/elastic/security-team/issues/6

- [ ] Open / Close all event count drop downs with an UI interaction https://github.com/elastic/endpoint-app-team/issues/493 [Mock v1] #151 -> closed by -> @monina-n @bkimmel PR: elastic/kibana#77819
- [ ] Increase the number of related events #75
- [ ] Showing all related events for nodes (currently responses are limited - 100 related events per node)
- [ ] Bug for related events limits - #127
- [ ] Investigate other data sources and ECS fields for generic Resolver #128
- [ ] Indicate the events the user clicked on #129 @michaelolo24

 - Normal process events
 - Alert events See #107 (comment)

Contacts: James Brown, Michael O., Kevin Qualters. Rob Austin.
