### ISSUE TITLE
[DOCS] 8.6.0 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2681]
### Description
Generate the 8.6.0 release notes and publish them before or on the release day, which is **December 13, 2022**.

### Milestone dates
- **FF:** November 15, 2022
- **BC:** November 16, 2022
- **Release:** December 13, 2022

### Checklist 

- [x] Open a PR for the Security release notes 
- [x] Add release notes PR to the docs release issue at https://github.com/elastic/dev/issues/2163
- [x] Set up the breaking changes section within the 8.6 release notes 
- [ ] Create a doc issue (optional) and PR for the breaking changes section in the Stack docs
- [ ] Complete the technical and editorial review for the Security release notes
- [ ] Merge the Security release notes PR 
- [ ] Merge the Stack docs PR

**Comment by jmikell821** [comment]
Adds the new Data Exfiltration Detection (DED) integration package (https://github.com/elastic/integrations/pull/4486).
