### ISSUE TITLE
[DOCS] New alert details page 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2687]
## Description 
In 8.10, we're introducing a redesigned version of the alert details flyout. The new flyout, called the _expandable flyout_, has three distinct UI components:
- **Right panel**: This area still contains the alert summary and three main tabs (Overview, Table, and JSON). The Overview tab contains much of the same information, but some sections have been renamed or newly added. 
- **Preview panel**: This panel shows more details about the rule. It allows users to view an expanded version of the rule summary and alert reason.
- **Left panel**: This panel contains three main tabs (Insights, Investigation, and Response) and multiple sub-tabs. Each tab displays more  more information about sections in the right panel. For example, if you wanted to learn more about a specific user or host that was mentioned in the Entities section within the right panel, you'd click the Entities button. This would expand expand the left panel, which would contain more details about the defined user and host. 

Related:
- https://github.com/elastic/security-team/issues/6313
- https://github.com/elastic/security-team/issues/4617
 
## Additional notes
- A breakdown of what's in each panel, section, and tab is [here](https://docs.google.com/document/d/1WWPluCN3ABdNBfYOoedL_aBC1bcswMjXx2Efv0CJxlU/edit).
- The workflow for accessing alert details in the expandable flyout has not changed. Users would still access the flyout from the Alert table.
- As of 8.10 BC2, the expandable flyout is _only_ being used in the Alert details page and the rule preview table (when previewing rule results).
- The expandable flyout might be turned on by default via the `securitySolution:enableExpandableFlyout` advanced setting in 8.10. 
   - [x] I'll check back with @PhilippeOberti and @michaelolo24 for a final decision on Tuesday, August 29 (or later in the week).
   - Expandable flyout _will_ be displayed/enabled by default in 8.10.
- Still need the following from @PhilippeOberti:
   - [ ] A central PR, or a group of them, that we can point to when release-note the expandable flyout.
   - [ ] A feature summary for release notes and possibly what's new in 8.10.

## Copy work
- https://github.com/elastic/ux-writing/issues/44
- https://github.com/elastic/kibana/issues/164786
- https://github.com/elastic/kibana/pull/164929
- https://github.com/elastic/kibana/pull/164930

## Doc updates
To accomodate for the size of this effort, I'm dividing it up into 2 separate tasks: alert details flyout docs rewrite and screenshot refreshes. 

### Task 1: Doc expandable flyout and new advanced setting
Write over the existing  [View detection alert details](https://www.elastic.co/guide/en/security/8.9/view-alert-details.html) page to avoid the need for redirects. I can also re-use existing content to cut down on new changes that'll need reviews. 
NOTE: Anything that needs to be significantly expanded or improved will need to be addressed in 8.11+.

#### Required doc updates
- [View detection alert details](https://www.elastic.co/guide/en/security/master/view-alert-details.html):
  - [x] Document each panel, section, and tab within the expandable flyout. 
  - [x] Within the page's intro para, add a note that points users towards previous versions of the page if they're still using the "old" alert details flyout.
- [Configure advanced settings](https://www.elastic.co/guide/en/security/master/advanced-settings.html):
  - [x] Document the **Expandable flyout** advanced setting (securitySolution:enableExpandableFlyout). Setting is enabled by default.

### Task 2: Update references to the alert details flyout and refresh screenshots
Refresh content that refers to the alert details flyout and refresh outdated screenshots.

#### Required doc updates
- [Add Osquery Response actions | Find query results](https://www.elastic.co/guide/en/security/master/osquery-response-action.html#find-osquery-response-action-results):
   - [x] The **Response Results** tab was renamed to **Results** in the expandable flyout. Will need to update the references (might be done in first task).
- [Session View | Open Session View](https://www.elastic.co/guide/en/security/master/session-view.html#open-session-view):
  - [x] Mention in intro that users can access Session View from the expandable flyout. Might need to add an example to the list in the section too.  
- [Visual event analyzer | find events to analyze](https://www.elastic.co/guide/en/security/master/visual-event-analyzer.html):
  - [x] Update step 3. Mention that users can analyze an event from the expandable flyout and link to those docs.

#### Required screenshot refreshes 
- Suppress detection alerts:
  - [x] [`suppressed-alerts-details.png`](https://www.elastic.co/guide/en/security/8.9/images/suppressed-alerts-details.png) (Need @PhilippeOberti's help getting the data for this screenshot) 
- Add Osquery Response Actions:
  - [x] [`osquery-results-tab.png`](https://www.elastic.co/guide/en/security/8.9/images/osquery-results-tab.png) 
- Host risk score: 
  - [x] [`score-in-flyout.png`](https://www.elastic.co/guide/en/security/8.9/images/score-in-flyout.png) (Need @PhilippeOberti's help getting the data for this screenshot) 
- User risk score: 
  - [x] [`urs-score-flyout.png`](https://www.elastic.co/guide/en/security/8.9/images/urs-score-flyout.png) (Need @PhilippeOberti's help getting the data for this screenshot) 
- Launch Timeline from investigation guides:
  - [x] [`ig-alert-flyout.png`](https://www.elastic.co/guide/en/security/8.9/images/ig-alert-flyout.png)

**Comment by nastasha-solomon** [comment]
Confirmed with @michaelolo24  that the new Alert details page was merged in 8.6. The page will be behind an internal feature flag that should not be exposed in feature docs or release notes/highlights.

**Comment by michaelolo24** [comment]
Yep, thanks @nastasha-solomon! Just making a note (for posterity) that currently it's only the summary view of that page that has been merged 😄

**Comment by nastasha-solomon** [comment]
Updating release version since this feature will not be released in 8.6.

**Comment by michaelolo24** [comment]
Thanks @nastasha-solomon !

**Comment by nastasha-solomon** [comment]
Not being released in 8.7. Is still being discussed/undergoing design changes and will being pushed to 8.8.

**Comment by nastasha-solomon** [comment]
The code for these changes will be merged in 8.8 but the feature flag will be off, which means the changes to the alert details flyout will not be public. Current plans are to turn the flag on in 8.9. In the meantime, I'll work with @PhilippeOberti to create a list of changes so we can start early planning of required doc updates.

cc: @michaelolo24

**Comment by PhilippeOberti** [comment]
> The code for these changes will be merged in 8.8 but the feature flag will be off, which means the changes to the alert details flyout will not be public. Current plans are to turn the flag on in 8.9. In the meantime, I'll work with @PhilippeOberti to create a list of changes so we can start early planning of required doc updates.
> 
> cc: @michaelolo24

@nastasha-solomon small correction: some of the code will be merged in 8.8 (we've been merging things for the last few weeks), but we'll keep it behind a feature flag (because we won't have time to merge everything)

**Comment by joepeeples** [comment]
Confirmed in mid-release demo that this will not be GA in 8.9 (behind feature flag, likely still developing). Keeping this issue in `8.9` for now so @nastasha-solomon has a chance to review as well.

**Comment by nastasha-solomon** [comment]
Verified with @paulewing today via Slack that we are _not_ changing the alert details flyout name in 8.10. Because of this, I'm removing the term refresh task from the doc plan and closed https://github.com/elastic/security-docs/pull/3815 without merging the changes.
