### ISSUE TITLE
[DOCS] Release Checklist (8.6)

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#2749]
Project boards/Meta checklists:

- D&R

   - Rules area: https://github.com/elastic/security-team/issues/5142

   - Alerts area: https://github.com/orgs/elastic/projects/698/views/19

- OLM  
   - https://github.com/elastic/security-team/issues/4793

- Threat Hunting

   - Investigations: https://github.com/orgs/elastic/projects/583/views/14

  - Explore: https://github.com/orgs/elastic/projects/711/views/1

- AWP: 
 
- Cloud Security Posture: 

- Platform: 

- ResponseOps | Cases: https://github.com/orgs/elastic/projects/611
  - NOTE: The finalized list of features is usually tracked in a google doc or [this project board](https://github.com/orgs/elastic/projects/731/views/4). In 8.6, Christos and Jonathan told me to reference the 8.6 column of the board and to only look at [the items that had the `Cases` label applied](https://github.com/orgs/elastic/projects/731/views/4?filterQuery=cases).
   

- Asset Management: https://github.com/orgs/elastic/projects/804/views/1

- Protections Experience: https://github.com/orgs/elastic/projects/804/views/1

Checklist:

- [ ] What's New?

     - [ ] Ensure include tags are included in file for inclusion in stack-docs [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

 

- [x] Release notes merged: 

 

- [ ] Merge `stack-docs` PR to ensure Security breaking changes are included in stack-docs: 

    **IMPORTANT:** Both of the following requirements must be met for the stack docs PR to build:

     - [ ] The 8.6 Security release notes PR merged into main and backported to the 8.6 branch.

     - [ ] The 8.6 Security release notes page will need to be built/published on the 8.6 branch and available on the public docs site.

 - [ ] Ensure all new navigation menu changes are updated in docs 

- [ ]  API changes merged

- [ ] D&R PRs merged and backported

- [ ]  Threat Hunting PRs merged and backported

- [ ] Endpoint PRs merged and backported

 - [ ] OLM PRs merged and backported

- [ ] AWP PRs merged and backported

- [ ] Cloud Security Posture PRs merged and backported

- [ ] ResponseOps PRs merged and backported

- [ ]  Bug issues addressed

- [ ] Update the docs release dev issue with appropriate PR numbers

- [ ]  Review and merge 8.6 prebuilt rules

- [ ]  Verify that merged doc updates display correctly in main and 8.6

**Comment by jmikell821** [comment]
`8.6.0` was released on Jan. 10 🎉
