### ISSUE TITLE
8.7.0 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2884]
### Description
Generate the 8.6.0 release notes and publish them before or on the release day, which is **February 7, 2023**.

### Milestone dates
- **FF:** February 7, 2023
- **BC1:** February 8, 2023
- **Release:** March 28, 2023

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes (can model the issue after https://github.com/elastic/security-docs/issues/2685)- https://github.com/elastic/security-docs/issues/2983
- [x] Add the release notes PR to the docs release issue - https://github.com/elastic/dev/issues/2214
- [x] Set up the breaking changes section within the 8.7 release notes 
- [x] Create a doc issue (optional) and PR for the breaking changes section in the Stack docs: https://github.com/elastic/stack-docs/issues/2351

#### Reviews
- [ ] Verify all Endpoint PRs are release-noted (check https://github.com/elastic/security-docs/issues/2983) 
- [ ] Complete the technical review 
   - [ ] Ensure all breaking changes are doc'd
   - [ ] Ensure all known issues and workarounds are doc'd 
- [ ] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 
- [ ] Merge the Stack docs PR 

### Notes
- https://github.com/elastic/kibana/pull/146373 - Only needs release notes
- https://github.com/elastic/kibana/pull/147628 - Possible summary: Removes fields that are not ECS-compliant before creating alerts. 
- https://github.com/elastic/kibana/pull/150181 - Don't need to release-note. This is flagged to be skipped, is part of a feature that hasn't been released yet, and doesn't present any notable user-facing changes.
- [x] @dhurley14 to create a doc issue that describes the following known issue: https://github.com/elastic/kibana/issues/150818 
   - [x] Document https://github.com/elastic/security-docs/issues/3046 as a known issue for 8.7. 
- [x] As per @MikePaquette's comment [here](https://github.com/elastic/security-team/issues/5766#issuecomment-1460989588), will need to mention CCS support for indicator match rules.
- [x] Will need to release-note https://github.com/elastic/kibana/pull/151952 as an enhancement.
