### ISSUE TITLE
[META] Alerts table/page updates for 8.7

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#2956]
## Description 

Several changes to the Alerts page and Alerts table for viewing multiple alerts. Currently some features are still being decided on for 8.7 release, technical preview, etc., so confirm before proceeding.

Related items for individual features:

- https://github.com/elastic/security-team/issues/5599 - New/revised/renamed histograms and charts
   - https://github.com/elastic/kibana/pull/149173 - Adds new charts and histograms to the Alerts Page

- https://github.com/elastic/kibana/pull/149145 - New feature for grouping alerts

- https://github.com/elastic/kibana/pull/147261 - Updates histograms so they render as Lens visualization (this work might be affected by the work being done in https://github.com/elastic/kibana/pull/146989. 146989 might also be a ticket to track design changes/decisions) 

- ~~https://github.com/elastic/security-team/issues/4128 - Drop-down filters at the top of the page~~ — UPDATE: Not included in 8.7?
   - ~~https://github.com/elastic/kibana/pull/146989 - Adds new filtering capabilities to the Alerts page.~~  — UPDATE: Not included in 8.7?

## Features, in a nutshell 🥜

- [x] Updated KPI visualizations (incl new Summary)
- [x] Alert grouping option in table
- [ ] ~~Histograms are Lens now (figure out what effect, if any, this has on user)~~ -- Behind feature flag `chartEmbeddablesEnabled`??

## Notes

- Consider whether to work on these together (same PR) or break out into sub-tasks. A lot (if not all) of these features will probably be documented in [Manage detection alerts](https://www.elastic.co/guide/en/security/master/alerts-ui-manage.html), so a single PR might be more straightforward. But there are so many feature changes, it might help to break up the workload. 🤷

**Comment by nastasha-solomon** [comment]
More related items for individual features:

- https://github.com/elastic/kibana/pull/147261 - Updates histograms so they render as Lens visualization (this work might be affected by the work being done in https://github.com/elastic/kibana/pull/146989. 146989 might also be a ticket to track design changes/decisions) 
- https://github.com/elastic/kibana/pull/149173 - Adds new charts and histograms to the Alerts Page
- https://github.com/elastic/kibana/pull/146989 - Adds new filtering capabilities to the Alerts page.

**Comment by joepeeples** [comment]
From 8.7 feature sync: follow up with @paulewing on definitions/parameters of `Detection` vs. `Prevention` alert types in new Summary visualization on Alerts page.
