### ISSUE TITLE
[BUG] Fix errors in the Endpoint Management API docs

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#2980]
## Description
[Docs](https://www.elastic.co/guide/en/security/8.6/event-filters-api.html) for the Event Filter API are outdated. Will need to fix the following:

- [x] The documented value for the `list_id` field is incorrect. It should be `endpoint_event_filters`, not `endpoint_events`. Will need to apply this fix across various reference tables and examples. (Can do this by updating the `list_id` attribute)
- [x] Need to specify that only one OS type can be used when creating an event filter. Will need to apply this fix to the [`os_types` values](https://www.elastic.co/guide/en/security/8.6/event-filters-api.html#exception-event-filter-item-os-types) section 
- [x] The documented value for the `type` field is incorrect in the [Create event filters container](https://www.elastic.co/guide/en/security/8.6/event-filters-api.html#_create_event_filters_container) section. It should be `endpoint_events`, not `endpoint`.  

Will also need to fix similar issues in the Host isolation Exceptions API docs:
_**Will fix this in a separate PR - decision [here](https://github.com/elastic/security-docs/pull/2982#issuecomment-1433430456)**_
- [x] The documented value for the `type` field is incorrect. It should be `endpoint_host_isolation_exceptions`, not `endpoint`. Will need to apply this fix across the [Create host isolation exceptions container](https://www.elastic.co/guide/en/security/master/host-isolation-exceptions-api.html#_create_host_isolation_exceptions_container) section.
   - Fixed in https://github.com/elastic/security-docs/pull/3001

  
## To-do

- [x] Review the Event Filter API docs - will work with @kevinlog's team to complete the doc audit
- [ ] Fix all bugs identified in the docs

## Notes
- The `list_id` value is a locally-defined attribute. It's been defined within the scope of the `event-filters-api.asciidoc` file so updating the attribute value updates all the places in topic where the attribute's used. 
-  The definition for the `os_types` field is not contained in the `event-filters-api.asciidoc` file. Instead, it's stored in the `exceptions-api-reusable-content.asciidoc` file and referenced by the `event-filters-api.asciidoc` file.
- The table in the [Create event filters container](https://security-docs_2982.docs-preview.app.elstc.co/guide/en/security/master/event-filters-api.html#_create_event_filters_container) and [Create host isolation exceptions container](https://security-docs_2982.docs-preview.app.elstc.co/guide/en/security/master/host-isolation-exceptions-api.html#_create_host_isolation_exceptions_container) docs reference [the same tagged section](https://github.com/elastic/security-docs/pull/2982/files#diff-d692e1c82fad400f2605747303488a205b1a2f01aee33df1f25f4125f09cb394L54) in the `_exceptions-api-reusable-content.asciidoc` file. Because of this, if I make any changes to the referenced section, the updates will show up in both docs. 
   - Potential solution: Create a new section with a new tag (`create-host-isolation-exception-container-request-body`) in the `_exceptions-api-reusable-content.asciidoc` file, change the `type` value from `endpoint_events` to `endpoint_host_isolation_exceptions`, and change the reference tag [here](https://github.com/elastic/security-docs/pull/2982/files#diff-8ee6b9cf73b58521bd8fb5c3dae8900aab2a0d004376d2c97cdf9f28533350d0L26) to `create-host-isolation-exception-container-request-body`.

**Comment by kevinlog** [comment]
@dasansol92 is going to review the PR and read through the rest of the existing Event Filters API docs to see if there are any other issues.

**Comment by dasansol92** [comment]
Hey @nastasha-solomon, thanks for working on fixing this.  I also noticed the list `type` must be `endpoint_events` and not `endpoint`. It has to be changed on the `Create event filters container` section.

**Comment by dasansol92** [comment]
Hey @nastasha-solomon , also noticed this `type` field is wrong for Host isolation Exceptions, it should be `endpoint_host_isolation_exceptions`. Can you change it in the same pr or do you want me to create a separated issue? Thanks!

**Comment by nastasha-solomon** [comment]
@dasansol92 I can bundle the change to the Host isolation Exceptions API docs into the same PR. I'll just add a note to this doc issue and the PR noting that the fix is related to the other doc updates we're making.
