### ISSUE TITLE
Docs Release Checklist (8.7)

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#3017]
### Project boards/Meta checklists:

- D&R

   - Rules area: https://github.com/elastic/security-team/issues/5543

   - Alerts area: https://github.com/orgs/elastic/projects/698/views/17
   
   - Platform: https://github.com/elastic/security-team/issues/5566

- Defend Workflows
   - https://github.com/elastic/security-team/issues/5360

- Asset Management 
   -  https://github.com/orgs/elastic/projects/804

- Threat Hunting

   - Investigations: https://github.com/orgs/elastic/projects/583/views/4

  - Explore: https://github.com/orgs/elastic/projects/711
  
- Cloud Security Team: https://github.com/orgs/elastic/projects/866/views/6 

- ResponseOps | Cases: https://github.com/orgs/elastic/projects/611  

### Checklist:

- [ ] What's New?

     - [ ] Ensure include tags are included in file for inclusion in stack-docs [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/security-highlights.html)

 

 - [ ] Release notes merged: 

 

- [ ] Merge `stack-docs` PR to ensure Security breaking changes are included in stack-docs: 

    **IMPORTANT:** Both of the following requirements must be met for the stack docs PR to build:

     - [ ] The `8.7` Security release notes PR merged into main and backported to the 8.7 branch.

     - [ ] The `8.7` Security release notes page will need to be built/published on the 8.7 branch and available on the public docs site.

 - [ ] Ensure all new navigation menu changes are updated in docs 

- [ ]  API changes merged

- [ ] D&R PRs merged and backported

- [ ]  Threat Hunting PRs merged and backported

- [ ] Endpoint PRs merged and backported

 - [ ] Defend Workflows/Asset Management PRs merged and backported

- [ ] Cloud Security Team PRs merged and backported

- [ ] ResponseOps PRs merged and backported

- [ ]  Bug issues addressed

- [ ] Update the [docs release dev issue](https://github.com/elastic/dev/issues/2214) with appropriate PR numbers

- [ ]  Review and merge `8.7` prebuilt rules

- [ ]  Verify that merged doc updates display correctly in main and `8.7`

**Comment by jmikell821** [comment]
8.7 is released! 🎉
