### ISSUE TITLE
8.8.0 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3139]
### Description
Generate the 8.8.0 release notes and publish them before or on the release day, which is **May 23, 2023**.

### Milestone dates
- **FF:** April 25, 2023
- **BC1:** April 26, 2023
- **Release:** May 23, 2023

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/3143
- [x] Add the release notes PR to the docs release issue
- [x] Set up the breaking changes section within the 8.8 release notes 
- [ ] Create a doc issue (optional) and PR for the breaking changes section in the Stack docs:  TBD

#### Reviews
- [ ] Verify all Endpoint PRs are release-noted 
- [ ] Complete the technical review 
   - [ ] Ensure all breaking changes are doc'd
   - [ ] Ensure all known issues and workarounds are doc'd 
- [ ] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 
- [ ] Merge the Stack docs PR 

### Notes
- The following PRs need to be ~removed from the Kibana release notes and moved to~ doc'd in the Security release notes:
  - [ ] https://github.com/elastic/kibana/pull/153213: Adds the Cloud_defend process index as a source and merged process event handling.
  - [ ] https://github.com/elastic/kibana/pull/154982: Fixes Session view and k8s dashboard 
- [x] We'll need to add the new `Team:Cloud Security` label to our release notes script to make sure we're pulling in Cloud Security PRs that are labeled for release notes.  
- Verify that these PRs are ok to be release-noted in kibana release notes only:
    - [x] https://github.com/elastic/kibana/issues/146864 and https://github.com/elastic/kibana/pull/150963: Users can add the Cases column to the Alerts table to view cases that alerts have been added to. This feature gives users an easy way to identify which cases certain alerts are being investigated in. 
    - [x] https://github.com/elastic/kibana/issues/130227 and https://github.com/elastic/kibana/issues/130227: Case activity and history is paginated and can be sorted. 
- These will need to be doc'd as a breaking change in 8.8:
    - [x] https://github.com/elastic/kibana/pull/147985: The privileges for attaching alerts to cases has changed. To attach alerts to cases, users now need `Read` access to Security, and `Write` access to the case. Refer to [summary](https://github.com/elastic/kibana/pull/155951/files#diff-6eabb97e98640429cb68b61823f99438d287d604d72ecf0e93ed2e9ecbec7479R74) in Kibana release notes for wording.
    - [x] API updates described [here](https://github.com/elastic/security-docs/issues/3257#issuecomment-1547151867) (@nastasha-solomon to provide release notes summary).
