### ISSUE TITLE
Changes to Security cases in 8.8

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3171]
## Description 

Using this doc issue to track changes related to Security cases in 8.8.

## Changes to document
- [x] https://github.com/elastic/kibana/issues/151595 and https://github.com/elastic/kibana/pull/154436: Users can attach files to cases. This doc update is being tracked in https://github.com/elastic/kibana/issues/154881 and will be made in the Security docs by @lcawl in https://github.com/elastic/security-docs/pull/3236. 
   - Attached files aren't exported as "related objects" when users export cases. Users will need to download the files from the case and re-upload them after they import the exported case. This limitation will prob need to mentioned in the feature docs.  
   - https://github.com/elastic/kibana/pull/154013: Allows users to set the min and max file size by setting two new fields the `kibana.yml` file:
     - `xpack.cases.files.allowedMimeTypes` - An array of strings representing the allowed mime types to be attached to a case.
     - `xpack.cases.files.maxSize` - A number representing the file size limit for files being attached to a case (in bytes).
- [x] https://github.com/elastic/kibana/issues/146864 and https://github.com/elastic/kibana/pull/150963: Users can add the Cases column to the Alerts table to view cases that alerts have been added to. This feature gives users an easy way to identify which cases certain alerts are being investigated in. Might be sufficient to doc this in the Kibana release notes only.
- [x] https://github.com/elastic/kibana/issues/130227 and https://github.com/elastic/kibana/issues/130227: Case activity and history is paginated and can be sorted. Refer to [#130227](https://github.com/elastic/kibana/issues/130227) for design and functionality details. 
- [x] https://github.com/elastic/kibana/pull/154626: Alerts table is GA in 8.8. Remove the warning note in the [Examine alerts attached to a case](https://www.elastic.co/guide/en/security/master/cases-open-manage.html#cases-examine-alerts) section.
- [x] https://github.com/elastic/kibana/pull/147985: The privileges for attaching alerts to cases has changed. To attach alerts to cases, users now need `Read` access to Security, and `Write` access to the case. Need to do the following:
   - [x] Might need to refresh the second row in the privs table in the [Case prerequisites](https://www.elastic.co/guide/en/security/master/case-permissions.html) topic.
   - [x] Possibly mention this breaking change in the Security release notes. It's currently doc'd in Kibana but might still need to mention in Security release notes because it's a change that directly affects Security cases. 

#### Screenshots/flows to update

Minor UI updates to the case details page will affect screenshots and flows doc'd in the [Open and manage cases](https://www.elastic.co/guide/en/security/master/cases-open-manage.html) topic:
  - The new **Files** tab was added after the **Alerts** tab. 
  - The **Alerts** tab no longer has an icon after it.
  - The case description is no longer part of the user history/activity thread.
  - The user history/activity thread is preceded by three tabs: 
     - **All**: Shows all comments and user activity/history.
     - **Comments**: Shows comments only. 
     - **History**: Shows the case's full history (includes actions, case status, ??)

<img width="800" alt="Screenshot 2023-04-30 at 3 30 20 PM" src="https://user-images.githubusercontent.com/79124755/235372703-14cd4fbd-3267-4161-9bfe-f8ce8882fe21.png">

The following screenshots will need to be refreshed:
NOTE: First four were updated in https://github.com/elastic/security-docs/pull/3236/files.
- [x] `cases-ui-open.png`
- [x] `cases-summary.png`
- [x] `cases-manage-comments.png` (not mandatory, but might be good to refresh anyways so it doesn't stick out from the other refreshed screenshots)
- [x] `cases-alert-tab.png`
- [ ] `add-vis-to-case.gif`
- [ ] `cases-open-vis.png` (not mandatory but might stick out if refreshed other screenshot)

Update these flows:
- [ ] Add a bullet to the [Manage existing cases](https://www.elastic.co/guide/en/security/master/cases-open-manage.html#cases-ui-manage) list that describes the different ways that users can view case activity and history.  

## Follow-up
Check on the following:
- [x] #3241
- [x] Get PRs for UI updates to the case details page.
- [ ] Confirm what's included in a case's history. What will users see when they click the **History** tab?
- [x] Clarify if `write` access = selecting the `All` setting for Cases. Currently, docs show that users need `All` privs for Cases.
- [x] ~Might need to update case priv docs to show what `Security` privs cases need for each level of access.~ Addressing https://github.com/elastic/security-docs/issues/3239 after 8.8.

## Notes
- The following issues/PRs will likely only need release notes and will be doc'd in the Kibana release notes:
  - https://github.com/elastic/kibana/issues/145514
  - https://github.com/elastic/kibana/pull/147985 (this will be doc'd as a breaking change in Kibana but likely does not affect the user experience when they're interacting with Security cases.)
