### ISSUE TITLE
8.8.2 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3414]
### Description
Generate the 8.8.2 release notes and publish them before or on the release day, which is ~**June 27, 2023**~ **June 29, 2023**.

**Milestone dates:**
- **FF:** June 20, 2023
- **BC:** June 21, 2023
- **Release:** ~June 27, 2023~ June 29, 2023 

### To-do:

- [x] Create the Security release notes PR: https://github.com/elastic/security-docs/pull/3472
- [x] File an issue and PR for updating the stack doc references to the breaking changes sections: https://github.com/elastic/stack-docs/pull/2443
- [ ] Merge https://github.com/elastic/stack-docs/pull/2443 after merging the 8.8.2 release notes PR. This will update the Security breaking changes section in the Stack docs install and upgrade guide.

### Steps 
1. Create a new branch using GH Desktop or the CLI. Here are the steps for the CLI: 
   a. From the CLI, run `git checkout main` to checkout the `main` branch.
   b. Run `git fetch origin` to retrieve the latest version of the `main` branch.
   c. Run `git pull` to pull down the latest changes in the `main` branch.
   d. Run `git checkout -b issue-XXX-8.8.2-rn` to create a new branch.
2. Open the Security docs project in your text editor (VS Code).
3. Expand the `release-notes` folder the open the `8.8.asciidoc` file.
4. At the top of the file, create a new section for the `8.8.2` release notes. Include the following sections: Bug fixes, breaking changes, and any other relevant sections.  
NOTE: Remove the tags from the 8.8.1 Breaking changes section and add them to the 8.8.2 section.

Example:

``` 
[discrete]
[[release-notes-8.8.2]]
=== 8.8.2

[discrete]
[[breaking-changes-8.8.2]]
==== Breaking changes  

//tag::breaking-changes[]
// NOTE: The breaking-changes tagged regions are reused in the Elastic Installation and Upgrade Guide. The pull attribute is defined within this snippet so it properly resolves in the output.
// THIS ALSO MEANS IF YOU USE LINKS HERE, THEY SHOULD BE FULL URLS WITH NO ATTRIBUTES

:pull: https://github.com/elastic/kibana/pull/

TBD.

//end::breaking-changes[]

[discrete]
[[enhancements-8.8.2]]
==== Enhancements
There are no user-facing changes in 8.8.2.

[discrete]
[[bug-fixes-8.8.2]]
==== Bug fixes 
* TBD
``` 

6. Open the `release-notes.asciidoc` file and insert a link to the `8.8.2` release notes, for example: `<<release-notes-v, {elastic-sec} version 8.8.2>>`
7. Save your changes.
8. Commit and push your changes:
   a. Run `git add --all` to add changes from all tracked and untracked files.
   b. Run `git commit -m "A brief description of your change"` to commit your changes. 
   c. Run `git push` to push your changes to the remote branch. If the branch doesn’t already exist in the remote repo, it is automatically created.
9. Open a PR in GH. Remember to add the `8.8` label so the release notes changes are backported to the 8.8 branch after you merge them into `main`.  

### Notes:
- These PRs will likely need to be added:
  - [ ] https://github.com/elastic/kibana/pull/157286 - Looks like the 8.8.2 tag was auto-added after the feature freeze.
  - [ ] https://github.com/elastic/kibana/pull/160451 - Couple notes on this one:
    - The team label on the PR shows that this is a ResponseOps team issue but the bug mainly affects [alert notification variables](https://www.elastic.co/guide/en/security/master/rules-ui-create.html#rule-response-action) for Security detection rules. Because it affects Security rules and not Kibana rules, this fix might need to be doc'd in the 8.8.2 Security release notes only. It'd also be good to check Lisa or Kaarina on this because their release notes script is configured to retrieve all PRs labeled with `Team:ReponseOps`. 
    - The bug described in https://github.com/elastic/kibana/issues/160446 might need to be doc'd as a known issue for 8.8.0 and 8.8.1. It looks like [one SDH](https://github.com/elastic/dev/issues/2299#issuecomment-1604686519) has been raised for this bug, so it might be good to release-note it. 
- @nastasha-solomon confirmed with @roxana-gheorghe that no Endpoint PRs needed to be release-noted for 8.8.2.
- If you add the PR to the Endpoint feature/bug/known issue, use the hardcoded URL to create the reference link. [Here](https://www.elastic.co/guide/en/security/8.3/release-notes-header-8.1.0.html#bug-fixes-8.1.2) is an example.
- ResponseOps features for cases, connectors, and alerts are always doc'd in the Kibana release notes _unless_ they are Security-specific features. This is also the case for Osquery feature and enhancements.
