### ISSUE TITLE
8.9.0 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3473]
### Description
Generate the 8.9.0 release notes and publish them before or on the release day, which is **July 25, 2023**.

### Milestone dates
- **FF:** June 20, 2023
- **BC1:** June 21, 2023
- **Release:** July 25, 2023

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/3474
- [x] Add the release notes PR to the docs release issue
- [x] Set up the breaking changes section within the 8.9 release notes
~NOTE: Remember to move the tags from the latest 8.8.x breaking changes section to the 8.9 breaking changes section.~ We'll be removing the breaking changes tags in [a separate PR](https://github.com/elastic/security-docs/pull/3605) so that we don't merge the 8.9 release notes with broken links.
- [x] Remove the breaking changes tags from 8.8.asciidoc file so the 8.9 Security breaking changes Stack docs [page](https://www.elastic.co/guide/en/elastic-stack/8.9/security-breaking-changes.html) only references the 8.9.asciidoc file (which contains the 8.9 breaking changes docs): https://github.com/elastic/security-docs/pull/3605
- [x] Create a doc issue (optional) and PR for the breaking changes section in the Stack docs: https://github.com/elastic/stack-docs/issues/2476 and https://github.com/elastic/stack-docs/pull/2477

#### Reviews
- [x] Verify all Endpoint PRs are release-noted 
- [x] Complete the technical review 
   - [x] Ensure all breaking changes are doc'd
   - [x] Ensure all known issues and workarounds are doc'd (known issues that haven't been fixed in the previous release should be carried forward)
- [x] Complete the editorial review 

#### Publishing
- [x] Merge the Security release notes PR 
- [x] Merge the Stack docs PR 

### Notes
- New features/enhancements to doc:
   - [x] Make sure to doc https://github.com/elastic/security-docs/issues/3540 as a new feature.
   - [x] https://github.com/elastic/security-docs/issues/3554 should be doc'd as a new enhancement. 
- Known issues to doc:
   - [x] https://github.com/elastic/security-docs/issues/3572 might be a known issue for 8.9. @nastasha-solomon is verifying this.
   - [x] https://github.com/elastic/endpoint-dev/pull/13278 - Might be fixed if there's another BC.
   - [x] https://github.com/elastic/security-docs/issues/3478 - Known issue is described in the "Known issue" section of the doc issue.
   - [x] https://github.com/elastic/security-docs/issues/3609 - See doc issue for more details.
- The following PRs might need to be doc'd as a deprecation in 8.9:
  - [x] https://github.com/elastic/detection-rules/pull/2901 (not in the Kibana repo, so the rn tool won't pick this up, even if it has the release notes label.)
- The following PRs need to be ~removed from the Kibana release notes and moved to~ doc'd in the Security release notes:
  - [x] None to report
- These will need to be doc'd as a breaking change in 8.9:
  - [x] https://github.com/elastic/kibana/pull/158094 (labeled for release notes, so all good to go!)

**Comment by nastasha-solomon** [comment]
Still doc'ing known issues.
