### ISSUE TITLE
[Meta Issue] UX Copy for Getting Started Hub

### ISSUE THREAD

**Issue by bfishel** [elastic/security-docs#3506]
## Description 
Our SaaS product aims to provide users with an easy and intuitive experience for configuring our application. To achieve this goal, we plan to create a centralized hub where users can access all necessary steps and information to configure our product. This hub will serve as a one-stop shop for users to easily complete their configuration process. 

The Security Design team needs guidance on copy for steps, step names, etc.

##Milestones
Copy review date 1: August 1, 2023
FF: August 31, 2023

## Acceptance Test Criteria
Approved by: Bonnie, relevant PMs
Final approval by: Dima and Gail

Analytics copy: Mike Paquette
Cloud copy: Sneha Sachidananda
EDR copy: Braden Preston

## Notes
[Figma](https://www.figma.com/file/jRYGkjocpS0uduIMuN4Inm/Getting-Started-Hub-%5BSecurity%5D?type=design&node-id=1610%3A139865&mode=design&t=WYJxYLyJu5z08fes-1)
[Google doc with steps and UX copy](https://docs.google.com/document/d/18GtetDwMzD3Sq4L_axrxbiV7kMeSJM3ZYlQ4I1ktS2A/edit?usp=sharing)

## Steps
- [ ] Invite users
- [ ] Introduction
- [ ] Bring in your data
- [ ] Activate and create rules
- [ ] Real-time protection for your environment 
- [ ] Get the most out of investigations workflow
- [ ] Respond to threats with automation
- [ ] Optimize your workspace

**Comment by benironside** [comment]
This was completed
