### ISSUE TITLE
8.10.0 Release notes

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#3657]
### Description
Generate the 8.10.0 release notes and publish them before or on the release day, which is **August 15, 2023**.

### Milestone dates
- **FF:** August 15, 2023
- **BC1:** August 16, 2023
- **Release:** September 10, 2023

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/3782
- [x] Add the release notes PR to the docs release issue

#### Reviews
- [x] Work with @roxana-gheorghe to verify all Endpoint PRs are release-noted 
- [x] Complete the technical review 
   - [x] Ensure all breaking changes are doc'd
   - [x] Ensure all known issues and workarounds are doc'd (known issues that haven't been fixed in the previous release should be carried forward)
- [x] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes: 
   - [x] None reported
- Known issues to doc:
   - [x] https://github.com/elastic/security-docs/issues/3904
