### ISSUE TITLE
[Meta] Update Security UI side nav

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#3694]
Related PR: https://github.com/elastic/kibana/pull/159185
Public issue: https://github.com/elastic/kibana/issues/157847

Major changes: 
- Former **Manage -> Rules** is moving to **Rules**. 
- **Manage -> Cloud Posture Benchmarks** is moving under **Rules -> Benchmark rules**. 
- **Manage -> Shared Exception lists** is moving under **Rules -> Shared Exception lists**. 

### SideNav package

- Styles updated according to the design
- New `categories` prop for the main panel links.
- New types of categories for the secondary panel links:
  - Title: Groups links under a category with a title label.
  - Separator: Groups links adding space with surrounding links
  - Accordion: Groups links in a EUI collapsible accordion (not used yet, will be needed for Serverless) 
- The `footerItems` component prop has been removed in favor of the `position?: 'top' | 'bottom' // default 'top'` item attribute.
- New `iconType` optional item attribute to display the icon next to the SideNav link. 
- All links texts now wrap instead of truncate.
- Links descriptions are no longer used.
- Secondary panel size updated, width reduced from `340px` to `270px`.

**Before**
![2023-08-17_13-58-28](https://github.com/elastic/security-docs/assets/57149392/f443619b-a7f2-4b50-ab70-8cd6c999bb23)

**After** 
![image](https://github.com/elastic/security-docs/assets/57149392/cb9dd784-95a0-4ca0-80eb-2815e8ba4b62)
![2023-08-17_14-04-34](https://github.com/elastic/security-docs/assets/57149392/19c40da8-9a1e-4a71-a904-c31705236d13)

```[tasklist]
### Topics to review for updates:
- [ ] [UI Overview](https://www.elastic.co/guide/en/security/current/es-ui-overview.html)
```

**Comment by nastasha-solomon** [comment]
@natasha-moore-elastic here are the notes I was going to add to my doc issue before I realized that I created a duplicate doc issue:
- The `Settings` section was re-named back to `Manage`.
- The `Cloud Posture Benchmarks` section was moved inside the `Rules` section (which you know was moved up a level to the main menu).
- @semd completed final changes on the main nav (for 8.10) in https://github.com/elastic/kibana/pull/163102.

**Comment by natasha-moore-elastic** [comment]
### Changes to be made

#### Update paths:
- [ ] **Manage -> Rules** to **Rules -> Detection rules (SIEM**)
- [ ] **Manage -> Cloud Posture Benchmarks** (currently documented as **Manage -> CSP Benchmarks**) to  **Rules -> Benchmark rules**
- [ ] **Manage -> Shared Exception lists** to **Rules -> Shared exception lists**

#### Update images/gifs that display the left nav:
- [Elastic Security UI](https://www.elastic.co/guide/en/security/current/es-ui-overview.html):
    - [ ] [images/nav-overview.gif](https://www.elastic.co/guide/en/security/current/images/nav-overview.gif)
    - [ ] [cloud-native-security/images/findings-page.png](https://www.elastic.co/guide/en/security/current/cloud-native-security/images/findings-page.png) (also on [Cloud security posture management > Findings page](https://www.elastic.co/guide/en/security/current/cspm-findings-page.html) and [Kubernetes security posture management > Findings page](https://www.elastic.co/guide/en/security/current/findings-page.html))
    - [ ] [manage-pg.png](https://www.elastic.co/guide/en/security/current/manage-pg.png)
- [AI Assistant](https://www.elastic.co/guide/en/security/current/security-assistant.html):
    - [ ] [images/assistant.gif](https://www.elastic.co/guide/en/security/current/images/assistant.gif)

#### Update content:
- [Elastic Security UI](https://www.elastic.co/guide/en/security/current/es-ui-overview.html):
    - [ ] Under **Manage**, remove Rules, Share Exception Lists, and CSP Benchmarks bullet points
    - [ ] swap **Cases** and **Timelines** sections
    - [ ] swap **Explore** and **Intelligence** sections
    - [ ] Between **Explore** and **Get started**, add a new **Rules** section
