### ISSUE TITLE
Update MITRE ATT&CK® version mentioned in the docs

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#4013]
## Description
With https://github.com/elastic/kibana/pull/166536, we'll need to update the MITRE ATT&CK® version mentioned in the note at the top of the [MITRE ATT&CK® coverage](https://www.elastic.co/guide/en/security/current/rules-coverage.html) page. The new version is `v13.1`.

This change was added to `8.10.3` and `8.11`, so we'll need to update the feature docs and release notes for both. 

Related:
- https://github.com/elastic/kibana/issues/166152 

## To-do
- [x] Feature docs updated for 8.10 and 8.11 via https://github.com/elastic/security-docs/pull/3983.  
- [x] Doc'd in 8.10.3 release notes via https://github.com/elastic/security-docs/pull/4011
- [x] Doc'd in 8.11 release notes via ~**TBD**~ - Removing this as a req for closing this issue since the feature doc updates are the highest priority items. The release notes docs will come later. 
- [x] Serverless docs updated via https://github.com/elastic/staging-serverless-security-docs/pull/187.

cc: @banderror @dplumlee @approksiu

**Comment by nastasha-solomon** [comment]
@banderror @dplumlee will the MITRE ATT&CK® coverage page in Serverless also use v13.1?

**Comment by nastasha-solomon** [comment]
Confirmed with @dplumlee via Slack that the MITRE ATT&CK® coverage page in Serverless _will_ be using v13.1. I'll open a separate PR against the Serverless docs to make this change. 
cc: @joepeeples

**Comment by nastasha-solomon** [comment]
All feature docs updated.
