### ISSUE TITLE
8.11.0 Release notes

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#4015]
### Description
Generate the 8.10.0 release notes and publish them before or on the release day, which is **November 7, 2023**.

### Milestone dates
- **FF:** October 3, 2023
- **BC1:** October 5, 2023
- **Release:** November 7, 2023

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/4005
- [x] Add the release notes PR to the docs release issue

#### Reviews
- [ ] Work with @roxana-gheorghe to verify all Endpoint PRs (fixes, known issues, breaking changes, and deprecations) are release-noted in Security release notes and Agent/Fleet (if needed).
- [ ] Complete the technical review 
   - [ ] Ensure all breaking changes are doc'd
   - [ ] Ensure all known issues and workarounds are doc'd (known issues that haven't been fixed in the previous release should be carried forward)
- [ ] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes: 
   - [ ] Will need to doc the `limit` param for the `top` command. More details [here](https://github.com/elastic/security-docs/issues/3889#issuecomment-1741434722).
- Known issues to doc:
   - [ ] TBD
- EA PRs are being tracked in https://github.com/elastic/security-docs/issues/4109

**Comment by yctercero** [comment]
NOTE: Breaking change for 8.11
In 8.11, detection engine APIs will only support `investigation_fields` as `{ field_names: string[] }`. Users exporting rules from 8.10 with this field, will still be able to import their rules into 8.11+ without needing to update the type.

@nastasha-solomon let me know if that makes sense.
