### ISSUE TITLE
[Meta] Entity Analytics content restructure 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#4117]
## Description 

This issue will be used to track major changes for Entity Analytics changes in `8.11`, which introduce a new detection engine and reorganizes existing docs. 

## Related info: 
- [Risk scoring Google doc](https://docs.google.com/document/d/1vKOEULMPxGB0piqBbRZTHoSkTCLjEmD14h7woE0rEAc/edit?usp=sharing)
- [EA Serverless issues and discussion Google doc](https://docs.google.com/document/d/14f4SwWWI4Dau-ZuYBnDJjKtYprC4ftUwpMUB5Zzfjf4/edit?usp=sharing)

## New doc structure (Phase 1)
Advanced entity analytics (L1) (new page)
 - Entity risk scoring (L2) (on same page as Advanced entity analytics)
      - Entity risk scoring algorithm (L3 section)
      - Enable the risk engine (L3) (new page, child page to Advanced entity analytics)
      - Upgrade to the latest risk engine (L3 section)
      - [Troubleshooting](https://www.elastic.co/guide/en/security/current/host-risk-score.html#troubleshoot-host-risk-score) (L3) (New topic, original risk engine only)
  - Analyze risk score data (new page, child page to Advanced entity analytics L2)
        

```[tasklist]
### Documentation Tasks
- [ ] https://github.com/elastic/security-docs/issues/4118
- [ ] https://github.com/elastic/security-docs/issues/4169
- [ ] https://github.com/elastic/security-docs/issues/4036
- [ ] https://github.com/elastic/security-docs/issues/4123
- [ ] https://github.com/elastic/security-docs/issues/4124
- [ ] https://github.com/elastic/security-docs/issues/4187
- [ ] https://github.com/elastic/security-docs/issues/4189
- [ ] https://github.com/elastic/security-docs/issues/4227
- [ ] https://github.com/elastic/security-docs/issues/4307
- [ ] https://github.com/elastic/security-docs/issues/4314
```
