### ISSUE TITLE
Endpoint artifact rollout

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#4163]
## Description 

Users can decide (turn on/off, set a time frame) when to upgrade artifacts on the endpoint; Including models, rules, etc.

* Related: https://github.com/elastic/security-team/issues/3593

```[tasklist]
### Pull requests
- [x] Classic docs PR: https://github.com/elastic/security-docs/pull/4261
- [x] Serverless docs PR: https://github.com/elastic/staging-serverless-security-docs/pull/230
```

```[tasklist]
### Tasks
- [x] Add new page for main feature docs
- [x] Update [Configure integration policy](https://www.elastic.co/guide/en/security/master/configure-endpoint-integration-policy.html): New tab on policy, link to new page
- [x] Update [Policies](https://www.elastic.co/guide/en/security/master/policies-page-ov.html) page: table now includes "Deployed version" column -- will be done in https://github.com/elastic/security-docs/pull/4234
- [x] Update screenshot in [Integration policy details](https://www.elastic.co/guide/en/security/current/admin-page-ov.html#integration-policy-details) to include the **Protection updates** tab -- will be done in #4263.
```
