### ISSUE TITLE
Entity Analytics: Create new "Advanced Behavioral Detections" topic

### ISSUE THREAD

**Issue by natasha-moore-elastic** [elastic/security-docs#4227]
Meta: https://github.com/elastic/security-docs/issues/4117
[Google doc reference with content drafts](https://docs.google.com/document/d/1vKOEULMPxGB0piqBbRZTHoSkTCLjEmD14h7woE0rEAc/edit#bookmark=id.vajixh4kn2tt)

## Description 

New TOC structure:

- Advanced Entity Analytics
  - Entity Risk Scoring
    - Turn on the risk scoring engine
    - View and analyze risk score data
  - Advanced Behavioral Detections
    - Anomaly detection
    - Optimizing anomaly results
    - Behavioral detection use cases
    - Prebuilt job reference

```[tasklist]
### Tasks - structure
- [x] Move [Entity Risk Scoring](https://www.elastic.co/guide/en/security/current/advanced-entity-analytics-overview.html#entity-risk-scoring) from the Advanced Entity Analytics page into a separate page, under Advanced Entity Analytics
- [x] Move [Turn on the risk scoring engine](https://www.elastic.co/guide/en/security/current/turn-on-risk-engine.html) and [View and analyze risk score data](https://www.elastic.co/guide/en/security/current/analyze-risk-score-data.html) under the Entity Risk Scoring page
- [x] Add new Advanced Behavioral Detections page under Advanced Entity Analytics
- [x] Add new Behavioral detection use cases page under Advanced Behavioral Detections
- [x] Move the [Anomaly detection with machine learning](https://www.elastic.co/guide/en/security/current/machine-learning.html) page under Advanced Behavioral Detections, and rename it to Anomaly detection
```

```[tasklist]
### Tasks - content
- [x] Update the [Advanced Entity Analytics](https://www.elastic.co/guide/en/security/current/advanced-entity-analytics-overview.html) page to mention two key areas of Advanced Entity Analytics: Entity Risk Scoring and Advanced Behavioral Detections, with links to the relevant child pages
- [x] Add an introduction section to the Advanced Behavioral Detections page, with links to the relevant child pages
- [x] On the Anomaly detection page, remove the [Jobs in Advanced Analytics (UEBA) Elastic integrations](https://www.elastic.co/guide/en/security/current/machine-learning.html#ml-integrations) section. Move this to the new Behavioral detection use cases page, including a link to the [Security: Elastic Integrations](https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html#security-integrations-jobs) section of the Prebuilt jobs reference page
- [x] Add an introduction section that defines use cases to the Behavioral detection use cases page
```
