### ISSUE TITLE
Add Buildkite to preview links GitHub action

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#4313]
## Description 

Per https://github.com/elastic/docs/pull/2837#issuecomment-1826264648, our PRs will start using Buildkite to generate previews but we'll need to revise our GitHub action ([docs-preview-links.yml](https://github.com/elastic/security-docs/blob/main/.github/workflows/docs-preview-links.yml)) to provide the URLs to those previews.

ℹ️ TIP: Follow https://github.com/elastic/docs/pull/2843, which looks to provide a common GitHub action template that all docs teams can use...
```[tasklist]
### Tasks
- [x] Add the new shared action — https://github.com/elastic/security-docs/pull/4390
- [x] Test it — https://github.com/elastic/security-docs/pull/4395
- [x] Remove the old action — https://github.com/elastic/security-docs/pull/4406
- [x] Test it again? — https://github.com/elastic/security-docs/pull/4411
- [x] Backport the changes so we can get previews in previous branches
```

```[tasklist]
### Backport PRs
- [ ] https://github.com/elastic/security-docs/pull/4421
- [ ] https://github.com/elastic/security-docs/pull/4430
- [ ] https://github.com/elastic/security-docs/pull/4429
- [ ] https://github.com/elastic/security-docs/pull/4428
- [ ] https://github.com/elastic/security-docs/pull/4427
- [ ] https://github.com/elastic/security-docs/pull/4426
- [ ] https://github.com/elastic/security-docs/pull/4425
- [ ] https://github.com/elastic/security-docs/pull/4424
- [ ] https://github.com/elastic/security-docs/pull/4423
- [ ] https://github.com/elastic/security-docs/pull/4422
- [ ] https://github.com/elastic/security-docs/pull/4420
- [ ] https://github.com/elastic/security-docs/pull/4419
- [ ] https://github.com/elastic/security-docs/pull/4418
```

**Comment by nkammah** [comment]
@joepeeples you should be able to use an action like [this one](https://github.com/elastic/elasticsearch-py/blob/e3d71055a97ab777877d5624f1e55a33158726ec/.github/workflows/docs-preview.yml) once https://github.com/elastic/docs/pull/2843 is merged. Comm is on its way.
