### ISSUE TITLE
[Detection Engine] Threshold rule alert suppression docs

### ISSUE THREAD

**Issue by vitaliidm** [elastic/security-docs#4315]
## Description 

- addresses milestone 1 of https://github.com/elastic/security-team/issues/7773 epic
- PR https://github.com/elastic/kibana/pull/171423

Few changes in comparison with custom query alerts suppression UI behaviour

1. Suppress by fields removed, since suppression is performed on Threshold Groups By fields
2. Instead, we show checkbox - so user can opt-in for alert suppression (either by selected threshold fields or w/o any)
3. Only time interval is radio button is available, suppression in rule execution is disabled(Threshold rule itself 'suppress' by grouping during rule execution)

Demo video, shows suppression on interval when users select threshold group by fields and when do not

https://github.com/elastic/kibana/assets/92328789/7dc476ad-0d0f-4e40-8042-d4dd552759d9

<details>
<summary>
Suppression is  enabled, threshold fields selected
</summary>
<img width="1056" alt="Screenshot 2023-11-27 at 16 44 04" src="https://github.com/elastic/kibana/assets/92328789/c654a7b2-6f70-4a04-8a85-48b2a2445014">
</details>

<details>
<summary>
Suppression is not enabled, threshold fields selected
</summary>
<img width="1036" alt="Screenshot 2023-11-27 at 16 44 27" src="https://github.com/elastic/kibana/assets/92328789/1cd4145f-df17-4b41-954b-c64de9eac0ff">
</details>

<details>
<summary>
Suppression is not enabled, threshold fields not selected
</summary>
<img width="1050" alt="Screenshot 2023-11-27 at 16 44 42" src="https://github.com/elastic/kibana/assets/92328789/8b64a65b-4abd-4334-a1a5-e2b00fe7d8a5">
</details>

Before doc published, feature is hidden behind `alertSuppressionForThresholdRuleEnabled` flag.
Available for ESS - Platinum license,  Serverless - Essentials

## Acceptance Test Criteria

 - UI behavior documented
 - Changes to API documented

```[tasklist]
### Docs PRs
- [x] Update classic docs — https://github.com/elastic/security-docs/pull/4467
- [x] Update serverless docs — https://github.com/elastic/staging-serverless-security-docs/pull/247
- [x] Update classic API docs — https://github.com/elastic/security-docs/pull/4479
```

```[tasklist]
### Tasks
- [x] Update [Create a threshold rule](https://www.elastic.co/guide/en/security/master/rules-ui-create.html#create-threshold-rule) steps to include new suppression options
- [x] Update [Suppress detection alerts](https://www.elastic.co/guide/en/security/master/alert-suppression.html) page to include threshold rule type, also revise some descriptions to be more generic (prepare for additional rule types, too)
- [x] Update [Reduce notifications and alerts](https://www.elastic.co/guide/en/security/master/reduce-notifications-alerts.html) to include threshold type / make generic
```

**Comment by joepeeples** [comment]
Threshold rule alert suppression docs are done. Semi-separately, we're also backporting API docs for the query rule alert suppression options, via https://github.com/elastic/security-docs/pull/4496 (issue https://github.com/elastic/security-docs/issues/4481), will be merged soon.
