### ISSUE TITLE
[Meta] Prebuilt rules in serverless docs [Serverless]

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#4352]
### Description

The [initial import](https://github.com/elastic/staging-serverless-security-docs/issues/10) of content into the docnav didn't include prebuilt rule docs, in order to focus on stabilizing product docs first. 

Also, we subsequently removed the files (https://github.com/elastic/staging-serverless-security-docs/issues/59) to avoid building and publishing unneeded pages.

We'll need to decide if we're going to add prebuilt rule docs into the serverless docs, or keep pointing to the classic docs.

Some tasks if we do end up adding them to serverless:

- [ ] Add prebuilt rule docs to the docnav structure so they'll be included in the side nav.
- [ ] Decide how to keep prebuilt rule docs pages updated per TRADE team's rule updates. This will probably require retooling of their current processes, so spin this into a separate task when ready.
- [ ] Restore/refactor links to prebuilt rule docs, which were commented out or otherwise revised in  https://github.com/elastic/staging-serverless-security-docs/issues/59.

### Background & resources

* Original staging issue: https://github.com/elastic/staging-serverless-security-docs/issues/23

### Which documentation set does this change impact?

Serverless only

### ESS release

N/A

### Serverless release

n/a

### Feature differences

Rules themselves work the same way, but we (or rather TRADE) would have to entirely rebuild the process for generating the docs for prebuilt rules.

### API docs impact

Probably n/a

### Prerequisites, privileges, feature flags

n/a

**Comment by joepeeples** [comment]
TRADE team is rebuilding this process via https://github.com/elastic/ia-trade-team/issues/120.
