### ISSUE TITLE
[META] Detection and Response docs checklist 

### ISSUE THREAD

**Issue by jmikell821** [elastic/security-docs#436]
Related issue: https://github.com/elastic/security-team/issues/437

- [ ] [Updates to rule actions API ](https://github.com/elastic/security-docs/issues/434)
- [x] [Support MITRE ATT&CK subtechniques in rule creation](https://github.com/elastic/security-docs/issues/432)
- [x] [Prebuilt rules for 7.11 ](https://github.com/elastic/security-docs/issues/433)
- [x] [Exception list features ](https://github.com/elastic/security-docs/issues/431)
- [x] [Detections Migration API](https://github.com/elastic/security-docs/issues/430)
- [x] [Add support for exceptions to ML Rules](https://github.com/elastic/security-docs/issues/427)
- [x] [Add section on using Value Lists with Indicator Match Rules](https://github.com/elastic/security-docs/issues/368)
- [ ] [Update Detections permissions to include maintenance for .siem-signals* index](#437)
- [x] [Document Detection Engine compatibility with Cold Tier storage and Searchable Snapshots](#446)
- [ ] [List of API changes for 7.11](#440) 
- [x] [Add alert source to detection rule action context](https://github.com/elastic/security-docs/issues/449)
- [x] [Add example of "current element' in alert placeholders](https://github.com/elastic/security-docs/issues/453)
