### ISSUE TITLE
[BUG] Remove unused images from serverless repo

### ISSUE THREAD

**Issue by joepeeples** [elastic/security-docs#4366]
**Description**: As a spin-off of https://github.com/elastic/security-docs/issues/4324, we have many image files in [staging-serverless-security-docs](https://github.com/elastic/staging-serverless-security-docs/tree/main/docs/images) that aren't being used in published docs, for one reason or another. We should remove as many as we can safely verify are truly not needed.

### Tasks

- [x] `obs-docs-helpers`: Use the "Find Unused Files" script to, you know, find the unused files.
- [x] Somehow verify that the files aren't being used anywhere, and removing them won't break anything.
- [x] Remove them.
- [x] Share and enjoy!
