### ISSUE TITLE
8.12.0 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#4380]
### Description
Generate the 8.12.0 release notes and publish them before or on the release day, which is **January 9, 2023**.

### Milestone dates
- **FF:** December 5, 2023
- **BC1:** December 7, 2023
- **Release:** January 9, 2024

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/4379
- [x] Add the release notes PR to the docs release issue: https://github.com/elastic/dev/issues/2441

#### Reviews
- [x] Work with @roxana-gheorghe to verify all Endpoint PRs (fixes, known issues, breaking changes, and deprecations) are release-noted in Security release notes and Agent/Fleet (if needed).
- [ ] Complete the technical review 
   - [x] Ensure all breaking changes are doc'd
   - [ ] Ensure all known issues and workarounds are doc'd (known issues that haven't been fixed in the previous release should be carried forward)
- [x] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes: 
   - [ ] TBD
- Known issues to doc:
   - [ ] Prebuilt rule update JSON diff displays internal properties (dev [issue](https://github.com/elastic/kibana/issues/174844) & [PR](https://github.com/elastic/kibana/pull/174789)) — https://github.com/elastic/security-docs/issues/4614

**Comment by nastasha-solomon** [comment]
@jmikell821 - just wanted to give you a heads up that @benironside and I are splitting up work on the 8.12 release notes as so:

- Ben is handling new features and enhancements
- Nastasha is doc'ing bug fixes, known issues, and Endpoint release notes

**Comment by nastasha-solomon** [comment]
Leaving myself a note that we'll need to doc the ES|QL tab feature flag (see https://github.com/elastic/security-docs/issues/4539) as new enhancement or bug fix in 8.12 as well. 

cc: @michaelolo24 @logeekal @PhilippeOberti
