### ISSUE TITLE
[Security docs] 7.9 doc updates (Ben's stuff)

### ISSUE THREAD

**Issue by benskelker** [elastic/security-docs#44]
Detailed list of all the doc things that need doing for 7.9:

- [x] ES Security overview flowchart: https://github.com/elastic/security-docs/issues/31
- [x] Cases/case connectors (Christos, Xavier):
   - [x] API: new external service: #64 
   - [x] UI: new connector type: #64 
- [x] Detection rules (Garrett, Ryland)
   - [x] API: update rule schema: #70 
   - [x] API: update signal (alert) schema: #70 
   - [x] UI: update create/modify rule procedure: #73 
   - [x] UI: new threshold rule type: #73 
   - [x] UI: new rule settings: #73 
   - [x] UI: screenshots: #73 
   - [x] Exception lists (Garrett, Frank, Yara, Ryland, Devin, Pedro):
        - [x] New API: https://github.com/elastic/security-docs/pull/35
        - [x] UI conceptual stuff and procedures #73 
   - [x] Prebuild rule updates (Craig/Paul): #66 
   - [x] New ML jobs (Craig): https://github.com/elastic/stack-docs/pull/1270
   - [x] Rename ML jobs (Craig): https://github.com/elastic/stack-docs/pull/1317
   - [x] Fix prolematic terminology used in the prebuild rule descriptions (UI only, docs have been fixed): https://github.com/elastic/detection-rules/pull/54
- [x] Timeline/Timeline templates (Angela, Xavier)
   - [x] Timeline object schema: https://github.com/elastic/security-docs/pull/50
   - [x] Timeline API: #50 
   - [x] New UI conceptual stuff and procedures: #84 
- [x] Update the SIEM section (including screenshots) in the Kibana UG: @DonNateR 
- [x] Rename SIEM > Elastic Security, Signals > Detection alerts (probably as part of a  few different PRs)
- [x] Restructure repo file system (probably as part of a few different PRs):
   - [x] Move APIs and reference sections to first level: https://github.com/elastic/security-docs/pull/18
- [x] Update in-app links to the docs: https://github.com/elastic/kibana/pull/71403, https://github.com/elastic/detection-rules/pull/54
   - [x] Map configuration
   - [x] Prebuilt rule metadata
   - [x] Others?
- [x] Check if the ECS section needs updating (Jamie, Mike)

**Comment by benskelker** [comment]
@jmikell821 @DonNateR - This is supposed to be a comprehensive list of all the things I need to do for the 7.9 release. If I don't make one, I forget things. Feel free to edit it.
