### ISSUE TITLE
8.13.0 Release notes

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#4713]
### Description
Generate the 8.13.0 release notes and publish them before or on the release day, which is **March 19, 2024**.

### Milestone dates
- **FF:** February 13, 2023
- **BC1:** February 15, 2023
- **Release:** March ~19~ 26, 2024

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/4714
- [x] Add the release notes PR to the docs release issue

#### Reviews
- [ ] Work with @roxana-gheorghe to verify all Endpoint PRs (fixes, known issues, breaking changes, and deprecations) are release-noted in Security release notes and Agent/Fleet (if needed).
- [ ] Complete the technical review 
   - [ ] Ensure all breaking changes are doc'd
   - [ ] Ensure all known issues and workarounds are doc'd (known issues that haven't been fixed in the previous release should be carried forward)
- [ ] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes: 
   - [ ] TBD
- Known issues to doc:
   - [ ] TBD
