### ISSUE TITLE
8.14.0 Release notes 

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#5042]
### Description
Generate the 8.14.0 release notes and publish them before or on the release day, which is ~**May 21, 2024**~ **June, 6, 2024**.

### Milestone dates
- **FF:** April 16, 2024
- **BC1:** April 18, 2024
- **Release:** ~May 21, 2024~ June 6, 2024

#### Prep/admin
- [x] Open a doc issue for Endpoint release notes: https://github.com/elastic/security-docs/issues/5043
- [x] Add the release notes PR to the docs release issue

#### Reviews
- [ ] Work with @roxana-gheorghe to verify all Endpoint PRs (fixes, known issues, breaking changes, and deprecations) are release-noted in Security release notes and Agent/Fleet (if needed).
- [ ] Complete the technical review 
   - [ ] Ensure all breaking changes are doc'd
   - [ ] Ensure all known issues and workarounds are doc'd (known issues that haven't been fixed in the previous release should be carried forward)
- [ ] Complete the editorial review 

#### Publishing
- [ ] Merge the Security release notes PR 

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes: 
   - [ ] TBD
- Known issues to doc:
   - [ ] TBD
- Follow up on these items:
   - [ ] Check with @paulewing on whether we want to highlight ES|QL features going GA
