### ISSUE TITLE
Add Scan command to response actions documentation [Request] 

### ISSUE THREAD

**Issue by caitlinbetz** [elastic/security-docs#5445]
### Description

We're introducing a "Scan" command in the response console in 8.15. The command will allow users to perform an on-demand scan of files in a directory. Once the action is submitted, the endpoint will run a scan of the files in that directory. The scan will proceed according to the policy settings associated with the endpoint - i.e. detect or prevent (or off), user blocklist on/off, etc - and will produce normal alerts to the alerts data stream (though without any process.* info since there is no acting process).

- Command syntax: scan --path <path>
  - Path is required; must be a string.
- The scan can and may run for an extended period of time, based on directory being scanned. 
- [ESS] Ability to run the Scan command will require specific scan privileges, configured in Kibana feature privileges
- Licensing: Enterprise [ESS], Endpoint Complete [Serverless]
- Scan execution and status (success/fail) are tracked in the response history

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/184723
* Issues/metas: https://github.com/elastic/security-team/issues/8887 (kibana side), https://github.com/elastic/endpoint-dev/issues/14216 (endpoint side)
* Point of contact: @ashokaditya , @ferullo, @caitlinbetz 
* Existing response actions doc: https://www.elastic.co/guide/en/security/current/response-actions.html

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.15

### Serverless release

~~Week of July 8, 2024~~ Soon after 8.15 release

### Feature differences

No feature differences; however, only specific Serverless roles can take response actions today. (I don't think capabilities for each role are explicitly documented anywhere - but just in case:)
* Tier 3 Analyst
* SOC Manager
* Endpoint Operations Analyst

### API docs impact

https://github.com/elastic/security-team/issues/8991

- New command accepted by response actions API to scan a directory
-  It accepts a directory/folder param that is mandatory and cannot be empty.
-  Command response will be success or failure, not scan results.
-  [ESS] It uses new Kibana feature sub-privilege for Scan operations
- Licensing: Enterprise [ESS], Endpoint Complete [Serverless]

### Prerequisites, privileges, feature flags

- Licensing: Enterprise [ESS], Endpoint Complete [Serverless]
- ESS:
    - Requires Scan Operations privilege (Kibana role feature privileges, under Security]
    - Feature flag: `xpack.securitySolution.enableExperimental: ['responseActionScanEnabled']` (per [kibana#184723](https://github.com/elastic/kibana/pull/184723))
- Serverless: Tier 3 Analyst, SOC Manager, Endpoint Operations Analyst

---

```[tasklist]
### Tasks & Pull Requests
- [x] ESS – Add `scan` to [response actions](https://www.elastic.co/guide/en/security/master/response-actions.html) page
- [x] ESS – Add `Scan Operations` to [features privileges](https://www.elastic.co/guide/en/security/master/endpoint-management-req.html) page
- [x] Serverless – Add `scan` to [response actions](https://www.elastic.co/docs/current/serverless/security/response-actions) page
- [ ] API docs – @ashokaditya to assist?
- [x] ESS product docs – https://github.com/elastic/security-docs/pull/5563
- [x] Serverless product docs – https://github.com/elastic/security-docs/pull/5566 (wait until 8.15 to merge)
- [x] Possibly revert ESS product docs – https://github.com/elastic/security-docs/pull/5621
```

**Comment by caitlinbetz** [comment]
Fyi @dasansol92

**Comment by paul-tavares** [comment]
@joepeeples  - correct. The `scan` command requires the Elastic Defend `v8.15.0` agent and that will not be available until 8.15 goes GA. As for the timing of when we might enable the Feature Flag in `main` (serverless), it could be +/- 1wk from 8.5 GA

cc/ @dasansol92 , @ferullo

**Comment by joepeeples** [comment]
Note to self: will need to split https://github.com/elastic/security-docs/pull/5563 into twin PRs for stateful & serverless
