### ISSUE TITLE
[Docs IA][ESS] Rework the Elastic Endpoint section 

### ISSUE THREAD

**Issue by benironside** [elastic/security-docs#5662]
### Description

As part of the [Security DOCS IA meta issue](https://github.com/elastic/docs-projects/issues/236), this issue tracks work on the Elastic Endpoint section of the Elastic Security docs (ESS).

We plan to make a new section based on the IA in [this document](https://docs.google.com/document/d/1TJ-0W1agfywm22dVD4JqID3NHYwxny-s9U3kafqle3A/edit). However, Joe and Nat may update that plan at their discretion.

Tentatively, this work will take place in two main stages:
- IA Updates: moving pages around, renaming sections and subsections
- Filling content gaps: expanding landing pages, writing missing pages, working on intro paragraphs

### Which documentation set does this change impact?

ESS and serverless

### ESS release

8.14 and later

### Serverless release

TBD, but as soon as possible after refactoring ESS, for better alignment.

---

```[tasklist]
### Tasks
- [x] Create TOC mockup — full TOC with all pages
- [x] Refactor IA — move pages, rename sections and subsections (rebuild the skeleton) — [security-docs#5707](https://github.com/elastic/security-docs/pull/5707)
- [x] Refactor serverless — [security-docs#5715](https://github.com/elastic/security-docs/pull/5715)
- [ ] Fill content gaps — expand landing pages, write missing pages, revise intro paragraphs (prob spin off into separate tasks for each gap)
- [x] Request redirects — submit redirects for any pages we remove, combine, or change URLs (submitted via web form)
- [ ] Refactor source files for easier maintenance?
- [ ] https://github.com/elastic/security-docs/issues/5750
```

**Comment by joepeeples** [comment]
We've completed the scope of this issue; filling content gaps will be separate tasks.
