### ISSUE TITLE
8.16.0 Release notes

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#5941]
### Description
Generate the 8.16.0 release notes and publish them before or on the release day.

### To-do 
- [x] Draft the release notes
- [x] Add the release notes PR the docs release issue
- [ ] Known issues:
   - Carry forward known issues that haven't been fixed yet
   - Update the summaries of known issues that were "fixed" in the current release (add fix details) 
- [ ] Merge the Security release notes PR 

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes: 
   - [ ] TBD
- Known issues to doc:
   - [ ] Manual rule runs: https://github.com/elastic/security-docs/issues/5264#issuecomment-2255420571
- Follow up on these items:
   - [ ] TBD
