### ISSUE TITLE
8.17.0 Release notes

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#6222]
### Description
Generate the 8.17.0 release notes and publish them before or on the release day.

### To-do
- [ ] Draft the release notes
- [ ] Add the release notes PR the docs release issue
- [ ] Known issues:
- Carry forward known issues that haven't been fixed yet
- Update the summaries of known issues that were "fixed" in the current release (add fix details)
- [ ] Merge the Security release notes PR

### Notes
- New features/enhancements that are outside of the `security-docs` repo and need release notes:
  - [ ] TBD
- Known issues to doc:
  - [ ] TBD
- Follow up on these items:
  - [ ] TBD
